### ISSUE TITLE
Circuit ID collisions

### ISSUE THREAD

**Issue by Marten4n6** [wbenny/mini-tor#13]
When reading your code I noticed for circuit IDs you simply increment an int:
https://github.com/wbenny/mini-tor/blob/5d39011e632be8e2b6b1819ee7295e8bd9b7a769/mini/tor/circuit.cpp#L1202-L1209
```
5.1.1. Choosing circuit IDs in create cells

   The CircID for a CREATE/CREATE2 cell is an arbitrarily chosen
   nonzero integer, selected by the node (OP or OR) that sends the
   CREATE/CREATE2 cell.  In link protocol 3 or lower, CircIDs are 2
   bytes long; in protocol 4 or higher, CircIDs are 4 bytes long.
```
When using an incrementing number, if the circuit ID is already in use, guard relays respond with ```RELAY_CONNECTED``` when performing the NTOR handshake instead of ```RELAY_RESOLVE``` (NTOR server handshake reply), this will cause issues.

I think it would be a good idea to make circuit IDs a random int with a maximum value of 2^31 (max C int value range for 4 bytes). Or am I missing something here?

**Comment by wbenny** [comment]
Circuit ID should be unique per your own single TCP connection. If you make 2^31 circuits without closing, then yeah, you'll run out of them (I assume you'd be kicked out by the relay waaay earlier). Using random numbers is recommended for security reasons and I'm aware of it. I used this approach for easier debugging.

**Comment by Marten4n6** [comment]
Thanks.
