### ISSUE TITLE
 Identifiers beginning with underscores are undefined behavior

### ISSUE THREAD

**Issue by fuchsia36** [wbenny/mini-tor#18]
I don't know if this is within the scope of the project either. But there are a lot of identifiers like _rendezvous_cookie, __xi_z, and __h. These are technically UB to create at file scope (except for the compiler), and identifiers with either two underscores or one underscore and a capital letter are UB for any use.

**Comment by wbenny** [comment]
`_rendezvous_cookie` isn't "one underscore and a capital letter" :)

Everyting in `crt0.cpp`, including `__xi_z` symbol, supplies - as the filename suggests - the default MSVC CRT. I didn't chose the names, they are chosen by MSVC compiler.

See here for more info: https://wiki.osdev.org/Visual_C%2B%2B_Runtime
