### ISSUE TITLE
Windows 7 32bit not working

### ISSUE THREAD

**Issue by iIIusi0n** [wbenny/mini-tor#26]
![image](https://user-images.githubusercontent.com/56464250/88683894-45075d00-d12f-11ea-8fcc-bb0c88ec6ebc.png)

always show this error. Windows 7 32bit vm.

**Comment by wbenny** [comment]
Win7 support has been dropped. Only Win8.1+ is supported.

Last version that has worked on Win7 can be found here: https://github.com/wbenny/mini-tor/tree/ms_crypto_api

**Comment by iIIusi0n** [comment]
Thank you sir. I will check it ;)

**Comment by Wyvern-Balls** [comment]
> Win7 support has been dropped. Only Win8.1+ is supported.
> 
> Last version that has worked on Win7 can be found here: https://github.com/wbenny/mini-tor/tree/ms_crypto_api

thanks for helped. but when i use fopen, fclose, fread, i got unresolved external symbol error.
